version: '3.3'

services:
   db:
     image: mariadb
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     ports:
       - "3307:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     container_name: wordpress
     depends_on:
       - db
     image: wordpresspostgres:latest
     volumes:
       - .:/var/www/html
     ports:
       - "80:80"
     restart: always
     environment:
       PHP_EXTENSION_XDEBUG: 1
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       PHP_IDE_CONFIG: serverName=wordpressX
       XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9899 idekey=VSCODE remote_connect_back=0 remote_autostart=0
volumes:
    dbdata: