<?php
if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
    'key' => 'group_56e84cde352ee',
    'title' => 'General Site Options',
    'fields' => array(
        array(
            'key' => 'field_infinite_pinned',
            'label' => 'Pinned Infinite Scroll Posts',
            'name' => 'posts',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'post',
            ),
            'taxonomy' => array(),
            'filters' => array(
                0 => 'search',
            ),
            'elements' => array(
                0 => 'featured_image',
            ),
            'min' => 0,
            'max' => 10,
            'return_format' => 'object',
        ),
        array(
            'key' => 'field_5b101d53c9e4d',
            'label' => 'Newsletter Survey Module',
            'name' => 'newsletter_survey_module',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'hp_module',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array(
            'key' => 'field_desktop_refresh',
            'label' => 'Desktop Refresh Timer',
            'name' => 'desktop_refresh_timer',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 30,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 15,
            'max' => 300,
            'step' => '',
        ),
        array(
            'key' => 'field_mobile_refresh',
            'label' => 'Mobile Refresh Timer',
            'name' => 'mobile_refresh_timer',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 30,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 15,
            'max' => 300,
            'step' => '',
        ),
        array(
            'key' => 'field_amp_refresh',
            'label' => 'Amp Refresh Timer',
            'name' => 'amp_refresh_timer',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 30,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 30,
            'max' => 300,
            'step' => '',
        ),
        array(
            'key' => 'field_lead1_refresh',
            'label' => 'Allow Lead 1 Refresh',
            'name' => 'allow_lead_1_refresh',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_lead2_refresh',
            'label' => 'Allow Lead 2 Refresh',
            'name' => 'allow_lead_2_refresh',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_box3_refresh',
            'label' => 'Allow Box 3 Refresh',
            'name' => 'allow_box_3_refresh',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_amp_lead2_refresh',
            'label' => 'Allow Amp Lead 2 Refresh',
            'name' => 'allow_amp_lead@_refresh',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options',
            ),
        ),
    ),
    'menu_order' => 2,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
    'modified' => 1463776864,
    'local' => 'php',
    ));
endif;
