<?php
if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
        'key'                   => 'group_599468834683d',
        'title'                 => 'Landing Page Options',
        'fields'                => array(
            array(
                'key'               => 'field_599468912d68a',
                'label'             => 'Tags & Terms',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_599469082d68c',
                'label'             => 'Parenting Page',
                'name'              => 'parenting_page',
                'type'              => 'true_false',
                'instructions'      => 'Is this a parenting/ ages & stages page?',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_599469782d68d',
                'label'             => 'Related Tags',
                'name'              => 'related_tags',
                'type'              => 'taxonomy',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'taxonomy'          => 'post_tag',
                'field_type'        => 'multi_select',
                'allow_null'        => 0,
                'add_term'          => 0,
                'save_terms'        => 1,
                'load_terms'        => 1,
                'return_format'     => 'id',
                'multiple'          => 0,
            ),
            array(
                'key'               => 'field_59946ab52d68e',
                'label'             => 'Parenting Stages',
                'name'              => 'parenting_stages',
                'type'              => 'taxonomy',
                'instructions'      => 'Please select all the parenting stages that will need to show on this page.',
                'required'          => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_599469082d68c',
                            'operator' => '==',
                            'value'    => '1',
                        ),
                    ),
                ),
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'taxonomy'          => 'stages',
                'field_type'        => 'multi_select',
                'allow_null'        => 0,
                'add_term'          => 0,
                'save_terms'        => 1,
                'load_terms'        => 1,
                'return_format'     => 'id',
                'multiple'          => 0,
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'page',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ));
endif;
