<?php
if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
        'key' => 'group_module_insertion_settings',
        'title' => 'Automatic Article Module Insertion Settings',
        'fields' => array(
            array(
                'key' => 'field_auto_modules',
                'label' => 'Modules',
                'name' => 'modules',
                'type' => 'relationship',
                'instructions' => 'Please select all the modules that you would like to be automatically inserted into articles',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'hp_module',
                ),
                'taxonomy' => array(),
                'filters' => array(
                    0 => 'search',
                ),
                'elements' => '',
                'min' => '',
                'max' => '',
                'return_format' => 'object',
            ),
            array(
                'key' => 'field_auto_modules_bottom',
                'label' => 'Article Bottom Modules',
                'name' => 'modules_bottom',
                'type' => 'relationship',
                'instructions' => 'Please select all the modules that you would like to be automatically inserted at the bottom of articles',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'hp_module',
                ),
                'taxonomy' => array(),
                'filters' => array(
                    0 => 'search',
                ),
                'elements' => '',
                'min' => '',
                'max' => '',
                'return_format' => 'object',
            ),
            array(
                'key' => 'field_auto_modules_repeating',
                'label' => 'Article Repeating Modules',
                'name' => 'modules_repeating',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Module',
                'sub_fields' => array(
                    array(
                        'key' => 'field_repeating_module',
                        'label' => 'Module',
                        'name' => 'repeating_module',
                        'type' => 'post_object',
                        'instructions' => 'Modules to insert',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'hp_module',
                        ),
                        'taxonomy' => array(),
                        'allow_null' => 0,
                        'multiple' => 1,
                        'return_format' => 'object',
                        'ui' => 1,
                    ),
                    array(
                        'key' => 'field_repeating_module_interval',
                        'label' => 'Repeat Interval',
                        'name' => 'repeating_module_interval',
                        'type' => 'range',
                        'instructions' => 'This module should be inserted after every how many paragraphs?',
                        'required' => 1,
                        'conditional_logic' => array(),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '1',
                        'min' => '1',
                        'max' => '20',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_repeating_module_max',
                        'label' => 'Max Allowed',
                        'name' => 'repeating_module_max',
                        'type' => 'number',
                        'instructions' => 'How many times can this module be inserted?',
                        'required' => 0,
                        'conditional_logic' => array(),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '0',
                        'min' => '0',
                        'max' => '99',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                    ),

                )
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-module-insertion-options',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
endif;
