<?php
if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
        'key' => 'group_5724a17055a62',
        'title' => 'Post Options',
        'fields' => array(
            array(
                'key' => 'field_5724a173c5e1d',
                'label' => 'Key Value',
                'name' => 'key_value',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_5735fab223e7d',
                'label' => 'Visibility on Home Page?',
                'name' => 'visibility_on_home_page',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'show' => 'Show',
                    'hide' => 'Hide',
                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => 'show',
                'layout' => 'vertical',
                'allow_null' => 0,
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_579041c4ce72f',
                'label' => 'Hide Sponsored Content?',
                'name' => 'hide_sponsored_content',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_57926c04000d5',
                'label' => 'Sponsored?',
                'name' => 'sponsored',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_57926c0e000d6',
                'label' => 'Sponsor Logo',
                'name' => 'sponsor_logo',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_57926c04000d5',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'sponsor_logo',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_57926c5a000d7',
                'label' => 'Sponsor Name',
                'name' => 'sponsor_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_57926c04000d5',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_57926c69000d8',
                'label' => 'Sponsor Link',
                'name' => 'sponsor_link',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_57926c04000d5',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_sponsored_post_impression_tracker',
                'label' => 'Impression Tracker',
                'name' => 'sponsored_post_impression_tracker',
                'type' => 'textarea',
                'instructions' => 'You must paste the whole tag in this field not just a link.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_57926c04000d5',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array(
                'key' => 'field_5968d0dec397b',
                'label' => 'Show Sponsor Name',
                'name' => 'show_sponsor_name',
                'type' => 'true_false',
                'instructions' => 'Check to show sponsor name in addition to image',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_57926c04000d5',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5967719f71f07',
                'label' => 'Not Safe for Advertisers',
                'name' => 'not_safe_for_advertisers',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_59839c2c22cfc',
                'label' => 'Disable drop cap',
                'name' => 'disable_drop_cap',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5a1d7ef94ff6f',
                'label' => 'GA Tags',
                'name' => 'ga_tags',
                'type' => 'text',
                'instructions' => 'This is where you can supply a comma separated list of tags you want to be tracked in Google Analytics with this post',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'tag1,tag2...',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
              'key' => 'field_5a26c2c877d17',
              'label' => 'Article Type',
              'name' => 'article_type',
              'type' => 'radio',
              'value' => null,
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array(
                'Default' => 'Default',
                'Feature' => 'Feature',
              ),
              'allow_null' => 0,
              'other_choice' => 0,
              'save_other_choice' => 0,
              'default_value' => 'Default Lead Type',
              'layout' => 'vertical',
              'return_format' => 'label',
            ),
            array(
                'key' => 'field_59839c2c33bfc',
                'label' => 'Hide Author line at bottom of article',
                'name' => 'hide_author_byline',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',

            ),

        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'campaign',
                ),
            ),
        ),
        'menu_order' => 10,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
endif;
