FROM artsper/php:7.2-fpm-node

RUN apt-get update && apt-get install -y unzip libxml2-dev git
RUN docker-php-ext-install simplexml
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN npm install
RUN npm i -g eslint

COPY ./app/.eslintrc.json /var/www/.selintrc.json
COPY ./app/composer.json /var/www/composer.json

WORKDIR /var/www

RUN composer install